version = 0.1
[default.deploy.parameters]
stack_name = "cloud-resume-backend"
resolve_s3 = true
s3_prefix = "cloud-resume-backend"
region = "us-east-1"
profile = "cloud-resume-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
