AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume Challenge Backend Stack

Globals:
  Function:
    Timeout: 10

Resources:
  VisitorCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ItemID
        Type: String

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/
      Handler: visitor_counter_lambda.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref VisitorCounterTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCounterTable
      Events:
        VisitorCountApi:
          Type: Api
          Properties:
            Path: /visitors
            Method: GET
            RestApiId: !Ref ServerlessRestApi

Outputs:
  VisitorApiEndpoint:
    Description: "API Gateway endpoint URL for Visitor Counter"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitors"


