# This is a GitHub Actions workflow file to deploy your frontend
name: Deploy Frontend to AWS S3 and CloudFront

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: gsocyberadmin
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AKIARVHTFHAPJ5KHKHYC }}
          aws-secret-access-key: ${{ qsDSSqlezS44mlt8WI8zs+kp9QulTuzOCkQP07UU }}
          aws-region: us-east-1 # Change to your AWS region

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://YOUR_S3_BUCKET_NAME --delete
        # Replace YOUR_S3_BUCKET_NAME with the name of your S3 bucket

      - name: Invalidate CloudFront distribution
        run: aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        # Replace YOUR_CLOUDFRONT_DISTRIBUTION_ID with your CloudFront ID
